name: Deploy to Kubernetes Cluster

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
    secrets:
      KUBECONFIG_DATA:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up kubeconfig
        run: |
          mkdir -p "$HOME/.kube"
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 --decode > "$HOME/.kube/config"
          chmod 600 "$HOME/.kube/config"

      - name: Verify Kubeconfig
        run: |
          kubectl config current-context
          kubectl get nodes

      - name: Install yq for YAML editing
        run: |
          sudo apt-get update && sudo apt-get install -y yq

      - name: Update image in deployment.yaml
        run: |
          yq eval ".spec.template.spec.containers[0].image = \"${{ inputs.image }}\"" -i k8s/deployment.yaml

      - name: Show updated deployment.yaml (for debugging)
        run: cat k8s/deployment.yaml

      - name: Dry-run validation of manifests
        run: |
          kubectl apply --dry-run=client -f k8s/deployment.yaml
          kubectl apply --dry-run=client -f k8s/service.yaml

      - name: Apply manifests to cluster
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Wait for rollout to complete
        run: |
          DEPLOY_NAME=$(yq eval ".metadata.name" k8s/deployment.yaml)
          kubectl rollout status deployment/$DEPLOY_NAME

      - name: Sanity Check - List Deployments
        run: kubectl get deploy

