name: Deploy to Kubernetes Cluster
on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
    secrets:
      KUBECONFIG_DATA:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up kubeconfig
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}
        run: |
          echo "$KUBECONFIG_DATA" | base64 -d > $HOME/.kube/config
      

      - name: Update image
        run: |
          sed -i "s|image:.*|image: ${{ inputs.image }}|" k8s/deployment.yaml

      - name: Apply manifests
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
