name: Dockerize

on:
  workflow_call:
    inputs:
      java_version:
        required: true
        type: string

jobs:
  dockerize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          echo "Setting up Docker (dummy step)"
          docker --version

      - name: Build Docker image (dummy)
        run: |
          echo "Building Docker image..."
          # docker build -t my-app:latest .
          echo "✅ Dummy Docker build complete"