name: Main Branch

on:
  workflow_call:
    inputs:
      java_version:
        default: 21
        required: false
        type: string
      image_name:
        required: true
        type: string
      sonar_project_key:
        required: true
        type: string
      sonar_organization:
        required: true
        type: string
    secrets:
      SONAR_TOKEN:
        required: false
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      java_version: ${{ steps.vars.outputs.java_version }}
      image_name: ${{ steps.vars.outputs.image_name }}
    steps:
      - name: Set variables
        id: vars
        run: |
          echo "java_version=${{ env.JAVA_VERSION }}" >> $GITHUB_OUTPUT
          echo "image_name=${{ env.IMAGE_NAME }}" >> $GITHUB_OUTPUT

  build:
    needs: setup
    uses: ./.github/workflows/build.yml
    with:
      java_version: ${{ inputs.java_version }}

  checkstyle:
    needs: build
    uses: ./.github/workflows/checkstyle.yml
    with:
      java_version: ${{ inputs.java_version }}

  snyk_scan:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Snyk Scan
        run: echo "Running Snyk security scan..."

  xray_scan:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Xray Scan
        run: echo "Running Xray vulnerability scan..."

  sonar_scan:
    needs: build
    uses: ./.github/workflows/sonar_scan.yml
    with:
      java_version: ${{ inputs.java_version }}
      sonar_project_key: ${{ inputs.sonar_project_key }}
      sonar_organization: ${{ inputs.sonar_organization }}
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  unit_tests:
    needs: build
    uses: ./.github/workflows/unit_tests.yml
    with:
      java_version: ${{ inputs.java_version }}

  integration_tests:
    needs: build
    uses: ./.github/workflows/integration_tests.yml
    with:
      java_version: ${{ inputs.java_version }}


  dockerize:
    needs: [ unit_tests, integration_tests ]
    uses: ./.github/workflows/dockerize.yml
    with:
      java_version: ${{ inputs.java_version }}
      image_name: ${{ inputs.image_name }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  deploy_dev_env:
    needs: dockerize
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to environment
        run: echo "Deploying to target environment..."

  smoke_tests_dev_env:
    needs: deploy_dev_env
    runs-on: ubuntu-latest
    steps:
      - name: Smoke & Regression Tests
        run: echo "Executing smoke & regression tests..."

  full_regression_dev_env:
    needs: smoke_tests_dev_env
    runs-on: ubuntu-latest
    steps:
      - name: Full Regression after DEV Deploy (Dummy)
        run: echo "Running full regression on DEV..."

  deploy_test_env:
    needs: dockerize
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to TEST
        run: echo "Deploying to TEST environment..."

  smoke_tests_test_env:
    needs: deploy_test_env
    runs-on: ubuntu-latest
    steps:
      - name: Smoke & Regression Tests
        run: echo "Executing smoke & regression tests..."

  full_regression_test_env:
    needs: smoke_tests_test_env
    runs-on: ubuntu-latest
    steps:
      - name: Full Regression after TEST Deploy (Dummy)
        run: echo "Running full regression on TEST..."

  deploy_stage_env:
    needs: dockerize
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Stage
        run: echo "Deploying to Stage environment..."

  smoke_tests_stage_env:
    needs: deploy_stage_env
    runs-on: ubuntu-latest
    steps:
      - name: Smoke & Regression Tests
        run: echo "Executing smoke & regression tests..."

  full_regression_stage_env:
    needs: smoke_tests_stage_env
    runs-on: ubuntu-latest
    steps:
      - name: Full Regression after Stage Deploy (Dummy)
        run: echo "Running full regression on Stage..."

  release_go_nogo:
    needs: full_regression_stage_env
    runs-on: ubuntu-latest
    steps:
      - name: Release Go/NoGo
        run: echo "Final Release Go/NoGo decision point."

  create_release_tag:
    needs: release_go_nogo
    runs-on: ubuntu-latest
    steps:
      - name: Create Release Tag
        run: echo "Creating release tag in version control."
