name: Sonar Scan

on:
  workflow_call:
    inputs:
      java_version:
        required: true
        type: string
    secrets:
      SONAR_TOKEN:
        required: true
jobs:
  sonar_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java ${{ inputs.java_version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.java_version }}

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=java_crud_service
            -Dsonar.organization=com.org.gk.tech
  
