name: Sonar Scan

on:
  workflow_call:
    inputs:
      java_version:
        required: true
        type: string
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  sonar_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java ${{ inputs.java_version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.java_version }}

      - name: Import SonarCloud SSL certificate
        run: |
          echo "Fetching SonarCloud certificate..."
          echo | openssl s_client -connect sonarcloud.io:443 -servername sonarcloud.io 2>/dev/null \
            | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > sonarcloud.crt

          echo "Importing certificate into Java truststore..."
          sudo keytool -import -trustcacerts -keystore "${JAVA_HOME}/lib/security/cacerts" \
            -storepass changeit -noprompt -alias sonarcloud -file sonarcloud.crt

      - name: SonarCloud Scan
        run: mvn clean verify sonar:sonar \
          -Dsonar.projectKey=java_crud_service \
          -Dsonar.organization=wqshmed-sonar \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.token=${{ secrets.SONAR_TOKEN }}
